version: "2"
volumes:
  database-data:
services:
  docker-ecosystem-node-service:
    image: ${REGISTRYHOST}/docker-ecosystem-node-service:${TAG}
    ports:
      - '5678'
    build: .
    links:
      - database
    depends_on:
      - migration
  migration:
    image: ${REGISTRYHOST}/docker-ecosystem-migration
    links:
      - database
  database:
    image: postgres:9.5.1
    volumes:
      - database-data:/var/lib/postgres/data
